CREATE TABLE IF NOT EXISTS diagnostico_leads (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  empresa VARCHAR(150) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  responsavel VARCHAR(150) NOT NULL,
  whatsapp VARCHAR(30) NOT NULL,
  email VARCHAR(150) NULL,
  pontuacao TINYINT UNSIGNED NOT NULL DEFAULT 0,
  classificacao ENUM('Muito Quente', 'Quente', 'Morno') NOT NULL DEFAULT 'Morno',
  origem VARCHAR(40) NOT NULL DEFAULT 'Direto',
  referer VARCHAR(255) NULL,
  status ENUM('Novo Lead', 'Em Contato', 'Proposta Enviada', 'Cliente Fechado', 'Encerrado') NOT NULL DEFAULT 'Novo Lead',
  respostas_json JSON NULL,
  clicou_whatsapp TINYINT(1) NOT NULL DEFAULT 0,
  whatsapp_clicked_at DATETIME NULL,
  ip_hash CHAR(64) NOT NULL,
  user_agent_hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_diagnostico_leads_created_at (created_at),
  INDEX idx_diagnostico_leads_status (status),
  INDEX idx_diagnostico_leads_classificacao (classificacao),
  INDEX idx_diagnostico_leads_origem (origem),
  INDEX idx_diagnostico_leads_visitante (ip_hash, user_agent_hash, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
