<?php
declare(strict_types=1);require_once __DIR__.'/_funcoes.php';exigir_permissao('resumo.visualizar');
$ano=max(2020,min(2100,(int)($_GET['ano']??$_POST['ano']??date('Y'))));$mes=max(1,min(12,(int)($_GET['mes']??$_POST['mes']??date('n'))));$erro='';
$s=$pdo->prepare('SELECT * FROM ponto_competencias WHERE ano=:ano AND mes=:mes');$s->execute([':ano'=>$ano,':mes'=>$mes]);$competencia=$s->fetch()?:['ano'=>$ano,'mes'=>$mes,'situacao'=>'aberta'];
if($_SERVER['REQUEST_METHOD']==='POST'){exigir_permissao('ponto.editar');validar_csrf();try{$acao=trim($_POST['acao']??'');$just=trim($_POST['justificativa']??'');if(!in_array($acao,['fechar','reabrir'],true))throw new RuntimeException('Ação inválida.');if($acao==='reabrir'&&$just==='')throw new RuntimeException('A reabertura exige justificativa.');$antes=$competencia;$usuario=ponto_admin_nome();
if($acao==='fechar'){if(($competencia['situacao']??'aberta')==='fechada')throw new RuntimeException('A competência já está fechada.');$sql="INSERT INTO ponto_competencias (ano,mes,situacao,fechado_em,fechado_por) VALUES (:ano,:mes,'fechada',NOW(),:usuario) ON DUPLICATE KEY UPDATE situacao='fechada',fechado_em=NOW(),fechado_por=VALUES(fechado_por),reaberto_em=NULL,reaberto_por=NULL,justificativa_reabertura=NULL";$pdo->prepare($sql)->execute([':ano'=>$ano,':mes'=>$mes,':usuario'=>$usuario]);}
else{if(($competencia['situacao']??'aberta')!=='fechada')throw new RuntimeException('A competência já está aberta.');$pdo->prepare("UPDATE ponto_competencias SET situacao='aberta',reaberto_em=NOW(),reaberto_por=:usuario,justificativa_reabertura=:just WHERE ano=:ano AND mes=:mes")->execute([':usuario'=>$usuario,':just'=>$just,':ano'=>$ano,':mes'=>$mes]);}
$s->execute([':ano'=>$ano,':mes'=>$mes]);$depois=$s->fetch()?:[];ponto_historico($pdo,'ponto_competencias',(int)($depois['id']??0),$acao==='fechar'?'fechamento':'reabertura',$antes,$depois,$just?:null);registrar_auditoria('ponto',$acao==='fechar'?'competencia_fechada':'competencia_reaberta','ponto_competencias',(int)($depois['id']??0),$antes,$depois,'sucesso',null,$just?:null);redirect("competencias.php?ano={$ano}&mes={$mes}&salvo=1");}catch(Throwable $e){$erro=ponto_mensagem_erro($e);}}
$s->execute([':ano'=>$ano,':mes'=>$mes]);$competencia=$s->fetch()?:['ano'=>$ano,'mes'=>$mes,'situacao'=>'aberta'];$q=$pdo->prepare('SELECT COUNT(*) FROM pontos_trabalho WHERE YEAR(data)=:ano AND MONTH(data)=:mes');$q->execute([':ano'=>$ano,':mes'=>$mes]);$total=(int)$q->fetchColumn();$fechada=$competencia['situacao']==='fechada';
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fechamento | SONI PONTO</title><link rel="stylesheet" href="<?=e(asset_url('assets/css/style.css'))?>"></head><body><?php ponto_render_header('SONI PONTO');?><main class="app-container"><section class="page-title"><span>SONI PONTO</span><h1>Fechamento mensal</h1></section><?php ponto_render_nav('competencias.php');?><?php if($erro):?><div class="alerta erro"><?=e($erro)?></div><?php endif;?><?php if(isset($_GET['salvo'])):?><div class="alerta sucesso">Situação da competência atualizada.</div><?php endif;?>
<section class="panel"><form class="ponto-filtros" method="get"><label>Mês<input type="number" min="1" max="12" name="mes" value="<?=$mes?>"></label><label>Ano<input type="number" min="2020" max="2100" name="ano" value="<?=$ano?>"></label><button>Revisar</button></form></section>
<div class="metrics-grid"><article class="metric-card <?=$fechada?'destaque':''?>"><span>Situação</span><strong><?=$fechada?'Fechada':'Aberta'?></strong></article><article class="metric-card"><span>Registros</span><strong><?=$total?></strong></article><article class="metric-card"><span>Competência</span><strong><?=sprintf('%02d/%04d',$mes,$ano)?></strong></article></div>
<section class="panel"><h2>Revisão</h2><p><a class="btn outline" href="resumo.php?mes=<?=$mes?>&ano=<?=$ano?>">Abrir resumo mensal</a></p><?php if($fechada):?><p>Fechada por <?=e((string)($competencia['fechado_por']??''))?> em <?=e((string)($competencia['fechado_em']??''))?>. Cadastro, edição e exclusão estão bloqueados no back-end.</p><?php else:?><p>Revise indicadores, alertas, RHID e direitos antes de fechar.</p><?php endif;?>
<?php if(usuario_pode('ponto.editar')):?><form method="post" onsubmit="return confirm('Confirma esta alteração de competência?');"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="ano" value="<?=$ano?>"><input type="hidden" name="mes" value="<?=$mes?>"><input type="hidden" name="acao" value="<?=$fechada?'reabrir':'fechar'?>"><?php if($fechada):?><label>Justificativa obrigatória<textarea name="justificativa" required></textarea></label><?php endif;?><button class="btn <?=$fechada?'':'danger'?>"><?=$fechada?'Reabrir competência':'Fechar competência'?></button></form><?php endif;?></section></main></body></html>
