<?php
declare(strict_types=1);require_once __DIR__.'/_funcoes.php';exigir_permissao('ponto.visualizar');
$erro='';$editar=(int)($_GET['editar']??0);$s=$pdo->prepare('SELECT * FROM ponto_direitos WHERE id=:id');$s->execute([':id'=>$editar]);$atual=$s->fetch()?:[];
if($_SERVER['REQUEST_METHOD']==='POST'){exigir_permissao('ponto.editar');validar_csrf();try{
$id=(int)($_POST['id']??0);$tipo=trim($_POST['tipo']??'');$situacao=trim($_POST['situacao']??'');$just=trim($_POST['justificativa_alteracao']??'');
if(!in_array($tipo,['folga_domingo','folga_feriado'],true)||!in_array($situacao,['pendente','agendada','utilizada','cancelada'],true))throw new RuntimeException('Tipo ou situação inválida.');
if($situacao==='cancelada'&&$just==='')throw new RuntimeException('Cancelamento exige justificativa.');
$origem=(int)($_POST['ponto_origem_id']??0);if($origem){$p=ponto_buscar_ponto($pdo,$origem);if(!$p)throw new RuntimeException('Ponto de origem inválido.');}
$dados=['ponto_origem_id'=>$origem?:null,'tipo'=>$tipo,'situacao'=>$situacao,'quantidade'=>ponto_decimal($_POST['quantidade']??''),'data_aquisicao'=>ponto_validar_data($_POST['data_aquisicao']??''),'data_prevista'=>trim($_POST['data_prevista']??'')?:null,'data_utilizacao'=>trim($_POST['data_utilizacao']??'')?:null,'observacao'=>trim($_POST['observacao']??''),'justificativa_alteracao'=>$just?:null];
if($dados['quantidade']<=0)throw new RuntimeException('A quantidade deve ser maior que zero.');if($situacao==='agendada'&&!$dados['data_prevista'])throw new RuntimeException('Direito agendado exige data prevista.');if($situacao==='utilizada'&&!$dados['data_utilizacao'])throw new RuntimeException('Direito utilizado exige data de utilização.');
if($id){$dados['id']=$id;$pdo->prepare('UPDATE ponto_direitos SET ponto_origem_id=:ponto_origem_id,tipo=:tipo,situacao=:situacao,quantidade=:quantidade,data_aquisicao=:data_aquisicao,data_prevista=:data_prevista,data_utilizacao=:data_utilizacao,observacao=:observacao,justificativa_alteracao=:justificativa_alteracao WHERE id=:id')->execute($dados);ponto_historico($pdo,'ponto_direitos',$id,'edicao',$atual,$dados,$just?:null);}
else{$pdo->prepare('INSERT INTO ponto_direitos (ponto_origem_id,tipo,situacao,quantidade,data_aquisicao,data_prevista,data_utilizacao,observacao,justificativa_alteracao) VALUES (:ponto_origem_id,:tipo,:situacao,:quantidade,:data_aquisicao,:data_prevista,:data_utilizacao,:observacao,:justificativa_alteracao)')->execute($dados);$id=(int)$pdo->lastInsertId();ponto_historico($pdo,'ponto_direitos',$id,'criacao',[],$dados);}
registrar_auditoria('ponto','direito_salvo','ponto_direitos',$id,$atual,$dados);redirect('direitos.php?salvo=1');}catch(Throwable $e){$erro=ponto_mensagem_erro($e);$atual=array_merge($atual,$_POST);}}
$lista=$pdo->query('SELECT d.*,p.data AS ponto_data FROM ponto_direitos d LEFT JOIN pontos_trabalho p ON p.id=d.ponto_origem_id ORDER BY d.data_aquisicao DESC,d.id DESC')->fetchAll();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Direitos | SONI PONTO</title><link rel="stylesheet" href="<?=e(asset_url('assets/css/style.css'))?>"></head><body><?php ponto_render_header('SONI PONTO');?><main class="app-container"><section class="page-title"><span>SONI PONTO</span><h1>Direitos compensatórios</h1></section><?php ponto_render_nav('direitos.php');?><?php if($erro):?><div class="alerta erro"><?=e($erro)?></div><?php endif;?><?php if(isset($_GET['salvo'])):?><div class="alerta sucesso">Direito salvo.</div><?php endif;?>
<?php if(usuario_pode('ponto.editar')):?><form method="post" class="panel form-grid two-cols"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)($atual['id']??0)?>"><label>Ponto de origem (ID)<input type="number" min="1" name="ponto_origem_id" value="<?=e((string)($atual['ponto_origem_id']??''))?>"></label><label>Tipo<select name="tipo"><option value="folga_domingo" <?=($atual['tipo']??'')==='folga_domingo'?'selected':''?>>Folga de domingo</option><option value="folga_feriado" <?=($atual['tipo']??'')==='folga_feriado'?'selected':''?>>Folga de feriado</option></select></label><label>Situação<select name="situacao"><?php foreach(['pendente','agendada','utilizada','cancelada'] as $v):?><option value="<?=$v?>" <?=($atual['situacao']??'pendente')===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></label><label>Quantidade<input name="quantidade" inputmode="decimal" value="<?=e((string)($atual['quantidade']??'1.00'))?>"></label><label>Aquisição<input type="date" name="data_aquisicao" required value="<?=e((string)($atual['data_aquisicao']??date('Y-m-d')))?>"></label><label>Data prevista<input type="date" name="data_prevista" value="<?=e((string)($atual['data_prevista']??''))?>"></label><label>Data utilizada<input type="date" name="data_utilizacao" value="<?=e((string)($atual['data_utilizacao']??''))?>"></label><label class="full">Observação<textarea name="observacao"><?=e((string)($atual['observacao']??''))?></textarea></label><label class="full">Justificativa da alteração/cancelamento<textarea name="justificativa_alteracao"><?=e((string)($atual['justificativa_alteracao']??''))?></textarea></label><button>Salvar direito</button></form><?php endif;?>
<section class="panel"><h2>Direitos registrados</h2><div class="table-wrap"><table><thead><tr><th>Aquisição</th><th>Tipo</th><th>Situação</th><th>Quantidade</th><th>Agenda/uso</th><th>Origem</th><th></th></tr></thead><tbody><?php foreach($lista as $d):?><tr><td><?=e(date('d/m/Y',strtotime($d['data_aquisicao'])))?></td><td><?=e($d['tipo']==='folga_feriado'?'Folga de feriado':'Folga de domingo')?></td><td><?=e((string)$d['situacao'])?></td><td><?=e((string)$d['quantidade'])?></td><td><?=e((string)($d['data_prevista']??''))?> <?=e((string)($d['data_utilizacao']??''))?></td><td><?=e($d['ponto_data']?date('d/m/Y',strtotime($d['ponto_data'])):'-')?></td><td><a href="?editar=<?=(int)$d['id']?>">Editar</a></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
