<?php
declare(strict_types=1);require_once __DIR__.'/_funcoes.php';exigir_permissao('ponto.visualizar');$erro='';
if($_SERVER['REQUEST_METHOD']==='POST'){exigir_permissao('ponto.editar');validar_csrf();try{
$id=(int)($_POST['id']??0);$s=$pdo->prepare('SELECT * FROM ponto_reembolsos_transporte WHERE id=:id');$s->execute([':id'=>$id]);$antes=$s->fetch();if(!$antes)throw new RuntimeException('Diferença não encontrada.');$acao=trim($_POST['acao']??'');$just=trim($_POST['justificativa']??'');$dados=$antes;$transicoes=['calculado'=>['solicitar','cancelar'],'solicitado'=>['aprovar','recusar','cancelar'],'aprovado'=>['pagar','cancelar'],'parcialmente_pago'=>['pagar','cancelar']];if(!in_array($acao,$transicoes[$antes['situacao']]??[],true))throw new RuntimeException('Ação incompatível com a situação atual.');
if(in_array($acao,['recusar','cancelar'],true)&&$just==='')throw new RuntimeException('Recusa ou cancelamento exige justificativa.');
$comprovante=ponto_upload_comprovante($_FILES['comprovante']??['error'=>UPLOAD_ERR_NO_FILE],$antes['comprovante']??null);
if($acao==='solicitar'){$valor=ponto_decimal($_POST['valor']??'');if($valor<=0)$valor=(float)$antes['diferenca_calculada'];$dados['situacao']='solicitado';$dados['valor_solicitado']=$valor;$dados['data_solicitacao']=date('Y-m-d H:i:s');}
elseif($acao==='aprovar'){$valor=ponto_decimal($_POST['valor']??'');if($valor<=0||$valor>(float)$antes['valor_solicitado'])throw new RuntimeException('Valor aprovado inválido.');$dados['situacao']='aprovado';$dados['valor_aprovado']=$valor;$dados['data_aprovacao']=date('Y-m-d H:i:s');}
elseif($acao==='pagar'){$valor=ponto_decimal($_POST['valor']??'');$forma=trim($_POST['forma_pagamento']??'');if($forma==='')throw new RuntimeException('Informe a forma de pagamento.');$pagamento=ponto_reembolso_situacao_pagamento((float)$antes['valor_aprovado'],(float)$antes['valor_reembolsado'],$valor);$dados['valor_reembolsado']=$pagamento['total'];$dados['situacao']=$pagamento['situacao'];$dados['data_pagamento']=date('Y-m-d H:i:s');$dados['forma_pagamento']=$forma;}
else{$dados['situacao']=$acao==='recusar'?'recusado':'cancelado';}
$dados['observacao']=trim($_POST['observacao']??$antes['observacao']??'');$dados['justificativa_alteracao']=$just?:($antes['justificativa_alteracao']??null);$dados['comprovante']=$comprovante;
$pdo->prepare('UPDATE ponto_reembolsos_transporte SET valor_solicitado=:valor_solicitado,valor_aprovado=:valor_aprovado,valor_reembolsado=:valor_reembolsado,situacao=:situacao,data_solicitacao=:data_solicitacao,data_aprovacao=:data_aprovacao,data_pagamento=:data_pagamento,forma_pagamento=:forma_pagamento,observacao=:observacao,justificativa_alteracao=:justificativa_alteracao,comprovante=:comprovante WHERE id=:id')->execute([':valor_solicitado'=>$dados['valor_solicitado'],':valor_aprovado'=>$dados['valor_aprovado'],':valor_reembolsado'=>$dados['valor_reembolsado'],':situacao'=>$dados['situacao'],':data_solicitacao'=>$dados['data_solicitacao'],':data_aprovacao'=>$dados['data_aprovacao'],':data_pagamento'=>$dados['data_pagamento'],':forma_pagamento'=>$dados['forma_pagamento'],':observacao'=>$dados['observacao'],':justificativa_alteracao'=>$dados['justificativa_alteracao'],':comprovante'=>$dados['comprovante'],':id'=>$id]);
$mapa=['solicitar'=>'solicitacao','aprovar'=>'aprovacao','pagar'=>'pagamento','recusar'=>'recusa','cancelar'=>'cancelamento'];ponto_historico($pdo,'ponto_reembolsos_transporte',$id,$mapa[$acao],$antes,$dados,$just?:null);registrar_auditoria('ponto','reembolso_'.$mapa[$acao],'ponto_reembolsos_transporte',$id,$antes,$dados);redirect('reembolsos.php?salvo=1');
}catch(Throwable $e){$erro=ponto_mensagem_erro($e);}}
$ano=max(2020,min(2100,(int)($_GET['ano']??date('Y'))));$mes=max(0,min(12,(int)($_GET['mes']??date('n'))));$loja=(int)($_GET['loja_id']??0);$situacao=trim($_GET['situacao']??'');$where=['YEAR(p.data)=:ano'];$params=[':ano'=>$ano];if($mes){$where[]='MONTH(p.data)=:mes';$params[':mes']=$mes;}if($loja){$where[]='r.loja_id=:loja';$params[':loja']=$loja;}if($situacao!==''){$where[]='r.situacao=:situacao';$params[':situacao']=$situacao;}$s=$pdo->prepare('SELECT r.*,p.data,l.codigo_loja,t.nome_trajeto FROM ponto_reembolsos_transporte r JOIN pontos_trabalho p ON p.id=r.ponto_id JOIN lojas_trabalho l ON l.id=r.loja_id LEFT JOIN trajetos_trabalho t ON t.id=r.trajeto_id WHERE '.implode(' AND ',$where).' ORDER BY p.data DESC,r.id DESC');$s->execute($params);$lista=$s->fetchAll();$lojas=ponto_lojas($pdo,false);$totais=['calculado'=>0,'solicitado'=>0,'aprovado'=>0,'pago'=>0,'recusado'=>0,'pendente'=>0];foreach($lista as $r){$totais['calculado']+=(float)$r['diferenca_calculada'];$totais['solicitado']+=(float)$r['valor_solicitado'];$totais['aprovado']+=(float)$r['valor_aprovado'];$totais['pago']+=(float)$r['valor_reembolsado'];if($r['situacao']==='recusado')$totais['recusado']+=(float)$r['diferenca_calculada'];$totais['pendente']+=ponto_reembolso_calculos((float)$r['valor_recebido'],(float)$r['valor_gasto'],(float)$r['valor_aprovado'],(float)$r['valor_reembolsado'])['saldo_reembolso'];}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reembolsos | SONI PONTO</title><link rel="stylesheet" href="<?=e(asset_url('assets/css/style.css'))?>"></head><body><?php ponto_render_header('SONI PONTO');?><main class="app-container"><section class="page-title"><span>SONI PONTO</span><h1>Diferenças de transporte</h1></section><?php ponto_render_nav('reembolsos.php');?><?php if($erro):?><div class="alerta erro"><?=e($erro)?></div><?php endif;?><?php if(isset($_GET['salvo'])):?><div class="alerta sucesso">Reembolso atualizado.</div><?php endif;?>
<section class="panel"><form method="get" class="ponto-filtros"><label>Ano<input type="number" name="ano" value="<?=$ano?>"></label><label>Mês<input type="number" min="0" max="12" name="mes" value="<?=$mes?>"></label><label>Loja<select name="loja_id"><option value="0">Todas</option><?php foreach($lojas as $l):?><option value="<?=(int)$l['id']?>" <?=(int)$l['id']===$loja?'selected':''?>><?=e((string)$l['codigo_loja'])?></option><?php endforeach;?></select></label><label>Situação<select name="situacao"><option value="">Todas</option><?php foreach(['calculado','solicitado','aprovado','parcialmente_pago','pago','recusado','cancelado'] as $v):?><option value="<?=$v?>" <?=$situacao===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><button>Filtrar</button></form></section>
<div class="metrics-grid"><?php foreach(['calculado'=>'Total calculado','solicitado'=>'Total solicitado','aprovado'=>'Total aprovado','pago'=>'Total reembolsado','recusado'=>'Recusado','pendente'=>'Saldo pendente'] as $k=>$l):?><article class="metric-card"><span><?=e($l)?></span><strong><?=e(ponto_moeda($totais[$k]))?></strong></article><?php endforeach;?></div><p><small>“Diferença pendente de conferência/reembolso” não representa reconhecimento automático de dívida trabalhista.</small></p>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Data/loja</th><th>Valores</th><th>Situação</th><th>Ação</th></tr></thead><tbody><?php foreach($lista as $r):?><tr><td><?=e(date('d/m/Y',strtotime($r['data'])))?><br><?=e((string)$r['codigo_loja'])?> <?=e((string)($r['nome_trajeto']??''))?></td><td>Previsto <?=e(ponto_moeda((float)$r['valor_previsto']))?><br>Recebido <?=e(ponto_moeda((float)$r['valor_recebido']))?><br>Gasto <?=e(ponto_moeda((float)$r['valor_gasto']))?><br><strong>Diferença <?=e(ponto_moeda((float)$r['diferenca_calculada']))?></strong><br>Pago <?=e(ponto_moeda((float)$r['valor_reembolsado']))?></td><td><?=e((string)$r['situacao'])?></td><td><?php if(usuario_pode('ponto.editar')&&!in_array($r['situacao'],['pago','recusado','cancelado'],true)):?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><select name="acao"><?php if($r['situacao']==='calculado'):?><option value="solicitar">Solicitar</option><?php endif;?><?php if($r['situacao']==='solicitado'):?><option value="aprovar">Aprovar</option><option value="recusar">Recusar</option><?php endif;?><?php if(in_array($r['situacao'],['aprovado','parcialmente_pago'],true)):?><option value="pagar">Registrar pagamento</option><?php endif;?><option value="cancelar">Cancelar</option></select><input name="valor" inputmode="decimal" placeholder="Valor"><input name="forma_pagamento" placeholder="Forma de pagamento"><textarea name="justificativa" placeholder="Justificativa quando obrigatória"></textarea><textarea name="observacao" placeholder="Observação"></textarea><input type="file" name="comprovante" accept=".pdf,.jpg,.jpeg,.png,.webp"><button>Aplicar</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
