<?php
declare(strict_types=1);require_once __DIR__.'/_funcoes.php';exigir_permissao('trajetos.visualizar');
$trajetoId=(int)($_GET['trajeto_id']??$_POST['trajeto_id']??0);$s=$pdo->prepare('SELECT t.*,l.codigo_loja,l.nome loja_nome FROM trajetos_trabalho t JOIN lojas_trabalho l ON l.id=t.loja_id WHERE t.id=:id');$s->execute([':id'=>$trajetoId]);$trajeto=$s->fetch();if(!$trajeto){http_response_code(404);exit('Trajeto não encontrado.');}$erro='';
if($_SERVER['REQUEST_METHOD']==='POST'){exigir_permissao('trajetos.editar');validar_csrf();try{$direcao=trim($_POST['direcao']??'');if(!in_array($direcao,['ida','volta'],true))throw new RuntimeException('Direção inválida.');$tarifa=ponto_decimal($_POST['tarifa_unitaria']??'');$quantidade=ponto_decimal($_POST['quantidade']??'');if($quantidade<=0)throw new RuntimeException('Quantidade deve ser maior que zero.');$dados=['trajeto_id'=>$trajetoId,'direcao'=>$direcao,'ordem_trecho'=>ponto_int($_POST['ordem_trecho']??''),'tipo_transporte'=>trim($_POST['tipo_transporte']??''),'descricao'=>trim($_POST['descricao']??''),'tarifa_unitaria'=>$tarifa,'quantidade'=>$quantidade,'subtotal'=>round($tarifa*$quantidade,2),'vigencia_inicio'=>ponto_validar_data($_POST['vigencia_inicio']??''),'vigencia_fim'=>trim($_POST['vigencia_fim']??'')?:null,'ativo'=>isset($_POST['ativo'])?1:0];if(!$dados['ordem_trecho']||$dados['tipo_transporte']==='')throw new RuntimeException('Ordem e tipo são obrigatórios.');$pdo->prepare('INSERT INTO trajeto_trechos_trabalho (trajeto_id,direcao,ordem_trecho,tipo_transporte,descricao,tarifa_unitaria,quantidade,subtotal,vigencia_inicio,vigencia_fim,ativo) VALUES (:trajeto_id,:direcao,:ordem_trecho,:tipo_transporte,:descricao,:tarifa_unitaria,:quantidade,:subtotal,:vigencia_inicio,:vigencia_fim,:ativo)')->execute($dados);$id=(int)$pdo->lastInsertId();ponto_historico($pdo,'trajeto_trechos_trabalho',$id,'alteracao_tarifa',[],$dados);registrar_auditoria('trajetos','trecho_criado','trajeto_trechos_trabalho',$id,[],$dados);redirect('trechos.php?trajeto_id='.$trajetoId.'&salvo=1');}catch(Throwable $e){$erro=ponto_mensagem_erro($e);}}
$s=$pdo->prepare('SELECT * FROM trajeto_trechos_trabalho WHERE trajeto_id=:id ORDER BY direcao,ordem_trecho,vigencia_inicio DESC');$s->execute([':id'=>$trajetoId]);$trechos=$s->fetchAll();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trechos | SONI PONTO</title><link rel="stylesheet" href="<?=e(asset_url('assets/css/style.css'))?>"></head><body><?php ponto_render_header('SONI PONTO');?><main class="app-container"><section class="page-title"><span><?=e((string)$trajeto['codigo_loja'])?></span><h1>Trechos — <?=e((string)$trajeto['nome_trajeto'])?></h1></section><?php ponto_render_nav('trajetos.php');?><?php if($erro):?><div class="alerta erro"><?=e($erro)?></div><?php endif;?><?php if(isset($_GET['salvo'])):?><div class="alerta sucesso">Trecho salvo.</div><?php endif;?>
<?php if(usuario_pode('trajetos.editar')):?><form method="post" class="panel form-grid two-cols"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="trajeto_id" value="<?=$trajetoId?>"><label>Direção<select name="direcao"><option value="ida">Ida</option><option value="volta">Volta</option></select></label><label>Ordem<input type="number" min="1" name="ordem_trecho" required></label><label>Tipo<input name="tipo_transporte" required placeholder="Ônibus, trem..."></label><label>Descrição<input name="descricao" placeholder="Linha ou integração"></label><label>Tarifa unitária<input name="tarifa_unitaria" inputmode="decimal" required></label><label>Quantidade<input name="quantidade" inputmode="decimal" value="1,00"></label><label>Vigência inicial<input type="date" name="vigencia_inicio" required value="<?=date('Y-m-d')?>"></label><label>Vigência final<input type="date" name="vigencia_fim"></label><label class="ponto-checkbox"><input type="checkbox" name="ativo" checked> Ativo</label><button>Adicionar trecho</button></form><?php endif;?>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Direção/ordem</th><th>Transporte</th><th>Composição</th><th>Subtotal</th><th>Vigência</th><th>Status</th></tr></thead><tbody><?php foreach($trechos as $t):?><tr><td><?=e((string)$t['direcao'])?> / <?=(int)$t['ordem_trecho']?></td><td><?=e((string)$t['tipo_transporte'])?><br><small><?=e((string)($t['descricao']??''))?></small></td><td><?=e((string)$t['quantidade'])?> × <?=e(ponto_moeda((float)$t['tarifa_unitaria']))?></td><td><?=e(ponto_moeda((float)$t['subtotal']))?></td><td><?=e((string)$t['vigencia_inicio'])?> — <?=e((string)($t['vigencia_fim']??'aberta'))?></td><td><?=((int)$t['ativo'])?'ativo':'inativo'?></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
